// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateResp struct {
	Id          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Created_at  string `json:"created_at"`
	Updated_at  string `json:"updated_at"`
}

type GetReq struct {
}

type GetResp struct {
	Id          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Created_at  string `json:"created_at"`
	Updated_at  string `json:"updated_at"`
}
