// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"projects/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/projects",
				Handler: GetProjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/projects",
				Handler: CreateProjectHandler(serverCtx),
			},
		},
	)
}
